apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: normal-service
  template:
    metadata:
      labels:
        app: normal-service
    spec:
      containers:
      - name: normal-service
        image: yasewang/normalservice
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: normal-service
spec:
  selector:
    app: normal-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30300
  type: NodePort