apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-deployment
spec:
  selector:
    matchLabels:
      app: fc-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: fc-deployment
    spec:
      nodeSelector:
        gpu: A10
      containers:
      - name: fc-crm
        image: 10.3.5.23:5000/k8s:java
        ports:
        - containerPort: 18501
        args:
        - java
        - -jar
        - /root/crm/funcun-crm-1.0-SNAPSHOT.jar
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 18501
          periodSeconds: 10
          # initialDelaySeconds: 60
        readinessProbe:
          httpGet: 
            path: /actuator/health
            port: 18501
          periodSeconds: 10
          # initialDelaySeconds: 60
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 18501
          failureThreshold: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 8
            memory: 2Gi
          limits:
            cpu: 16
            memory: 4Gi
      - name: fc-py
        image: 10.3.5.23:5000/k8s:py
        ports:
        - containerPort: 13000
        - containerPort: 18350
        - containerPort: 18400
        - containerPort: 18450
        - containerPort: 18600
        args:
        - /bin/sh
        - /root/start.sh
        livenessProbe:
          httpGet:
            path: /check
            port: 18350
          periodSeconds: 10
          # 有启动探针可以不指定容器启动延迟检测
          # initialDelaySeconds: 60
        readinessProbe:
          httpGet: 
            path: /check
            port: 18350
          periodSeconds: 10
          # initialDelaySeconds: 60
        startupProbe:
          httpGet:
            path: /check
            port: 18350
          failureThreshold: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 16
            memory: 32Gi
          limits:
            cpu: 32
            memory: 64Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fc-service
spec:
  selector:
    app: fc-deployment
  ports:
  - port: 18501
    targetPort: 18501
    nodePort: 30300
  type: NodePort