name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install -g yarn
        yarn
        yarn run docs:build
      env:
        CI: true
    - name: build image
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/yasewang/blog:latest .
    - name: push image
      run: |
        docker login -u 554332816@qq.com -p ${{ secrets.DOCKER_PWD_ALI }} registry.cn-hangzhou.aliyuncs.com
        docker push registry.cn-hangzhou.aliyuncs.com/yasewang/blog:latest
