name: build

on: [push]

jobs:
  build-docs:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install -g yarn
        yarn
        yarn run docs:build
    - name: show
      run: |
        pwd
        ls
        ls ./docs/.vuepres
  image:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Check File
        run: |
          ls
    
